import { useMemo, useRef, useState } from 'react';
import type { LayoutChangeEvent, NativeScrollEvent, NativeSyntheticEvent } from 'react-native';
import { Dimensions, Image, Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { images, type IconName } from './assets';
import { BodyText, Frame, Icon } from './components';
import { features, milestones, navigation, products, technologySteps } from './content';
import { colors, fonts } from './theme';

const HERO_PRODUCTS_RATIO = 1050 / 877;
const WEARABLE_RATIO = 1536 / 1024;

type Dialog = { title: string; text: string; image?: 'app' | 'wearable' } | null;
type SectionName = 'story' | 'technology' | 'ecosystem' | 'features' | 'roadmap' | 'contact';

function useViewport() {
  const [width, setWidth] = useState(Dimensions.get('window').width);
  useState(() => {
    const sub = Dimensions.addEventListener('change', ({ window }) => setWidth(window.width));
    return () => sub.remove();
  });
  return width;
}

export function WeCareSite() {
  const width = useViewport();
  const mobile = width < 680;
  const tablet = width < 1060;
  const tiny = width < 390;
  const scrollRef = useRef<ScrollView>(null);
  const sections = useRef<Partial<Record<SectionName, number>>>({});
  const [menuOpen, setMenuOpen] = useState(false);
  const [dialog, setDialog] = useState<Dialog>(null);
  const [progress, setProgress] = useState(0);

  const scrollTo = (name: SectionName) => {
    setMenuOpen(false);
    scrollRef.current?.scrollTo({ y: Math.max(0, (sections.current[name] ?? 0) - 18), animated: true });
  };

  const onScroll = (event: NativeSyntheticEvent<NativeScrollEvent>) => {
    const { contentOffset, contentSize, layoutMeasurement } = event.nativeEvent;
    setProgress(Math.min(1, Math.max(0, contentOffset.y / Math.max(1, contentSize.height - layoutMeasurement.height))));
  };
  const record = (name: SectionName) => (event: LayoutChangeEvent) => { sections.current[name] = event.nativeEvent.layout.y; };

  return (
    <View style={s.app}>
      <View pointerEvents="none" style={[s.progress, { width: `${progress * 100}%` }]} />
      <ScrollView ref={scrollRef} style={s.scroll} contentContainerStyle={s.scrollContent} onScroll={onScroll} scrollEventThrottle={16}>
        <Hero mobile={mobile} tablet={tablet} tiny={tiny} menuOpen={menuOpen} setMenuOpen={setMenuOpen} navigate={scrollTo} openDialog={setDialog} />
        <Manifesto mobile={mobile} />
        <Ecosystem mobile={mobile} tablet={tablet} onLayout={record('ecosystem')} openDialog={setDialog} />
        <Technology mobile={mobile} onLayout={record('technology')} progress={progress} />
        <Capabilities mobile={mobile} tablet={tablet} onLayout={record('features')} />
        <HumanStory mobile={mobile} onLayout={record('story')} openDialog={setDialog} />
        <Roadmap mobile={mobile} onLayout={record('roadmap')} />
        <Closing mobile={mobile} onLayout={record('contact')} openDialog={setDialog} />
        <Footer mobile={mobile} navigate={scrollTo} />
      </ScrollView>
      <InfoModal dialog={dialog} mobile={mobile} close={() => setDialog(null)} />
    </View>
  );
}

function Hero({ mobile, tablet, tiny, menuOpen, setMenuOpen, navigate, openDialog }: { mobile: boolean; tablet: boolean; tiny: boolean; menuOpen: boolean; setMenuOpen: (value: boolean) => void; navigate: (name: SectionName) => void; openDialog: (dialog: Dialog) => void }) {
  const productWidth = mobile ? 300 : tablet ? 450 : 620;
  return (
    <View style={[s.heroShell, mobile && s.heroShellMobile]}>
      <Image source={images.technology} resizeMode="cover" style={s.heroTexture} />
      <View pointerEvents="none" style={s.heroGrid} />
      <Frame mobile={mobile} style={s.heroFrame}>
        <View style={s.header}>
          <Pressable accessibilityRole="link" onPress={() => navigate('story')}><Image source={images.logoReverse} resizeMode="contain" style={[s.logo, mobile && s.logoMobile]} /></Pressable>
          {!mobile ? <View style={s.navigation}>{navigation.slice(0, 5).map((item) => <NavLink key={item.target} label={item.label} dark onPress={() => navigate(item.target)} />)}<SmallAction label="Trải nghiệm" onPress={() => openDialog({ title: 'Trải nghiệm WeCare', text: 'Thiết bị đeo, ứng dụng và AI kết nối thành một hành trình theo dõi sức khỏe chủ động.', image: 'app' })} /></View> : <Pressable accessibilityRole="button" accessibilityLabel="Mở menu" onPress={() => setMenuOpen(!menuOpen)} style={s.menuButton}><Icon name={menuOpen ? 'close' : 'menu'} color={colors.white} size={23} /></Pressable>}
        </View>
        {mobile && menuOpen ? <View style={s.mobileMenu}>{navigation.map((item) => <NavLink key={item.target} label={item.label} onPress={() => navigate(item.target)} mobile />)}</View> : null}
        <View style={[s.heroContent, mobile && s.heroContentMobile]}>
          <View style={[s.heroCopy, mobile && s.heroCopyMobile]}>
            <Text accessibilityRole="header" style={[s.heroTitle, tablet && s.heroTitleTablet, mobile && s.heroTitleMobile, tiny && s.heroTitleTiny]}>Lắng nghe{`\n`}từng chuyển động.</Text>
            <Text style={[s.heroBody, mobile && s.heroBodyMobile]}>WeCare chuyển tín hiệu vận động mỗi ngày thành sự thấu hiểu, để hành trình chăm sóc Parkinson bắt đầu sớm hơn, bình tĩnh hơn.</Text>
            <View style={s.actionRow}><PrimaryAction label="Khám phá hệ sinh thái" onPress={() => navigate('ecosystem')} /><OutlineAction label="Xem cách hoạt động" onPress={() => navigate('technology')} /></View>
          </View>
          <View pointerEvents="none" style={[s.heroProductZone, mobile && s.heroProductZoneMobile]}>
            <View style={[s.productHalo, mobile && s.productHaloMobile]} />
            <Image source={images.heroProducts} resizeMode="contain" style={[s.heroProducts, { width: productWidth, height: productWidth * HERO_PRODUCTS_RATIO }]} />
            {!mobile ? <Text style={s.heroProductNote}>A quiet companion{`\n`}for every day.</Text> : null}
          </View>
        </View>
        <Pressable accessibilityRole="button" onPress={() => navigate('story')} style={[s.scrollPrompt, mobile && s.scrollPromptMobile]}><View style={s.scrollLine} /><Text style={s.scrollText}>Cuộn để khám phá</Text></Pressable>
      </Frame>
    </View>
  );
}

function Manifesto({ mobile }: { mobile: boolean }) {
  return <View style={[s.manifesto, mobile && s.manifestoMobile]}><Frame mobile={mobile}><Text style={s.manifestoIndex}>01 / WECARE</Text><Text accessibilityRole="header" style={[s.manifestoTitle, mobile && s.manifestoTitleMobile]}>Công nghệ chỉ có ý nghĩa khi nó giúp con người sống chủ động và gần nhau hơn.</Text><View style={[s.manifestoFoot, mobile && s.manifestoFootMobile]}><View style={s.mintDot} /><BodyText style={s.manifestoText}>Một thiết bị nhỏ. Một góc nhìn rõ hơn về sức khỏe. Một sự đồng hành dài lâu cho cá nhân, gia đình và bác sĩ.</BodyText></View></Frame></View>;
}

function Ecosystem({ mobile, tablet, onLayout, openDialog }: { mobile: boolean; tablet: boolean; onLayout: (event: LayoutChangeEvent) => void; openDialog: (dialog: Dialog) => void }) {
  const stations = useMemo(() => products.map((product, index) => ({ ...product, index })), []);
  return <View onLayout={onLayout} style={[s.ecosystem, mobile && s.ecosystemMobile]}><Frame mobile={mobile}>
    <View style={[s.splitHeading, mobile && s.splitHeadingMobile]}><Text style={s.sectionNumber}>02</Text><View style={s.headingCopy}><Text accessibilityRole="header" style={[s.sectionTitle, mobile && s.sectionTitleMobile]}>Một hệ sinh thái{`\n`}đủ gần để thấu hiểu.</Text><BodyText style={s.sectionLead}>Từ cảm biến trên cổ tay đến báo cáo có thể chia sẻ, mỗi điểm chạm được thiết kế để tạo một bức tranh sức khỏe liền mạch.</BodyText></View></View>
    <View style={[s.orbitStage, mobile && s.orbitStageMobile]}>
      <View style={[s.orbitOuter, mobile && s.orbitOuterMobile]} /><View style={[s.orbitInner, mobile && s.orbitInnerMobile]} />
      <Pressable accessibilityRole="button" accessibilityLabel="Mở ứng dụng WeCare" onPress={() => openDialog({ title: 'Ứng dụng WeCare', text: products[1].text, image: 'app' })} style={[s.orbitCore, mobile && s.orbitCoreMobile]}><Image source={images.phone} resizeMode="contain" style={s.orbitPhone} /></Pressable>
      {stations.map((station) => <OrbitStation key={station.title} station={station} mobile={mobile} tablet={tablet} onPress={() => openDialog({ title: station.title, text: station.text, image: station.index === 0 ? 'wearable' : station.index === 1 ? 'app' : undefined })} />)}
    </View>
  </Frame></View>;
}

function OrbitStation({ station, mobile, tablet, onPress }: { station: (typeof products)[number] & { index: number }; mobile: boolean; tablet: boolean; onPress: () => void }) {
  const placement = mobile ? [s.stationMobileA, s.stationMobileB, s.stationMobileC, s.stationMobileD][station.index] : tablet ? [s.stationTabletA, s.stationTabletB, s.stationTabletC, s.stationTabletD][station.index] : [s.stationA, s.stationB, s.stationC, s.stationD][station.index];
  return <Pressable accessibilityRole="button" onPress={onPress} style={({ pressed }) => [s.station, placement, pressed && s.pressed]}><Text style={s.stationOrdinal}>0{station.index + 1}</Text><Text style={s.stationTitle}>{station.title}</Text><View style={s.stationArrow}><Icon name="arrow" size={13} color="#BFF6D6" /></View></Pressable>;
}

function Technology({ mobile, onLayout, progress }: { mobile: boolean; onLayout: (event: LayoutChangeEvent) => void; progress: number }) {
  return <View onLayout={onLayout} style={[s.technology, mobile && s.technologyMobile]}><Image source={images.technology} resizeMode="cover" style={s.coverBackground} /><View pointerEvents="none" style={s.techShade} /><Frame mobile={mobile} style={s.technologyFrame}>
    <View style={[s.techHeading, mobile && s.techHeadingMobile]}><Text style={s.sectionNumberDark}>03</Text><View style={s.headingCopy}><Text accessibilityRole="header" style={[s.techTitle, mobile && s.techTitleMobile]}>Khi dữ liệu{`\n`}trở thành sự thấu hiểu.</Text><BodyText dark style={s.techLead}>Một dòng chảy kín đáo, bảo mật và liên tục biến chuyển động đời thường thành thông tin có ích cho hành trình chăm sóc.</BodyText></View></View>
    <View style={[s.dataRail, mobile && s.dataRailMobile]}>{technologySteps.map((step, index) => <DataNode key={step.title} step={step} index={index} mobile={mobile} lift={mobile ? 0 : ((index % 2 ? 1 : -1) * (8 + Math.round(progress * 18)))} />)}</View>
  </Frame></View>;
}

function DataNode({ step, index, mobile, lift }: { step: (typeof technologySteps)[number]; index: number; mobile: boolean; lift: number }) {
  return <View style={[s.dataNode, mobile && s.dataNodeMobile, { transform: [{ translateY: lift }] }]}><View style={s.dataNumber}><Text style={s.dataNumberText}>0{index + 1}</Text></View><View style={s.dataIcon}><Icon name={step.icon as IconName} size={mobile ? 25 : 29} color="#D9FFE8" /></View><Text style={s.dataTitle}>{step.title}</Text><Text style={s.dataText}>{step.text}</Text>{!mobile && index < technologySteps.length - 1 ? <View style={s.dataConnector}><View style={s.dataConnectorDot} /></View> : null}</View>;
}

function Capabilities({ mobile, tablet, onLayout }: { mobile: boolean; tablet: boolean; onLayout: (event: LayoutChangeEvent) => void }) {
  return <View onLayout={onLayout} style={[s.capabilities, mobile && s.capabilitiesMobile]}><Frame mobile={mobile}>
    <View style={[s.capabilityIntro, mobile && s.capabilityIntroMobile]}><Text style={s.sectionNumber}>04</Text><Text accessibilityRole="header" style={[s.sectionTitle, mobile && s.sectionTitleMobile]}>Sự chủ động,{`\n`}được thiết kế nhẹ nhàng.</Text></View>
    <View style={s.capabilityList}>{features.map((feature, index) => <View key={feature.title} style={[s.capabilityRow, mobile && s.capabilityRowMobile, !mobile && tablet && { width: '48%' }]}><Text style={s.capabilityNumber}>0{index + 1}</Text><View style={s.capabilityIcon}><Icon name={feature.icon as IconName} size={25} /></View><View style={s.capabilityCopy}><Text style={s.capabilityTitle}>{feature.title}</Text><BodyText style={s.capabilityText}>{feature.text}</BodyText></View></View>)}</View>
  </Frame></View>;
}

function HumanStory({ mobile, onLayout, openDialog }: { mobile: boolean; onLayout: (event: LayoutChangeEvent) => void; openDialog: (dialog: Dialog) => void }) {
  return <View onLayout={onLayout} style={[s.humanStory, mobile && s.humanStoryMobile]}><View style={[s.storyImageWrap, mobile && s.storyImageWrapMobile]}><Image source={images.care} resizeMode="cover" style={s.storyImage} /><View pointerEvents="none" style={s.storyImageShade} /><Text style={s.storyCaption}>Những chuyển động nhỏ{`\n`}tạo nên cuộc sống lớn.</Text></View><View style={[s.storyPanel, mobile && s.storyPanelMobile]}><Text style={s.sectionNumber}>05</Text><Text accessibilityRole="header" style={[s.storyTitle, mobile && s.storyTitleMobile]}>Phát hiện sớm.{`\n`}Đồng hành lâu dài.</Text><BodyText style={s.storyText}>WeCare tin rằng mỗi tín hiệu được nhận ra sớm có thể mở thêm cơ hội cho một cuộc sống độc lập, trọn vẹn và an tâm hơn.</BodyText><OutlineAction label="Câu chuyện WeCare" darkText onPress={() => openDialog({ title: 'Câu chuyện WeCare', text: 'Chúng tôi theo đuổi một tương lai nơi công nghệ vận động giúp người dùng hiểu sức khỏe của mình sớm hơn và chủ động hơn.' })} /></View></View>;
}

function Roadmap({ mobile, onLayout }: { mobile: boolean; onLayout: (event: LayoutChangeEvent) => void }) {
  return <View onLayout={onLayout} style={[s.roadmap, mobile && s.roadmapMobile]}><Frame mobile={mobile}><View style={[s.roadmapHeading, mobile && s.roadmapHeadingMobile]}><Text style={s.sectionNumber}>06</Text><View style={s.headingCopy}><Text accessibilityRole="header" style={[s.sectionTitle, mobile && s.sectionTitleMobile]}>Lộ trình{`\n`}để trưởng thành.</Text><BodyText style={s.roadmapLead}>Từng bước đi của WeCare được dẫn dắt bằng nghiên cứu, lắng nghe và sự cẩn trọng của y học.</BodyText></View></View><View style={s.timeline}>{milestones.map((milestone, index) => <View key={milestone.title} style={[s.timelineItem, mobile && s.timelineItemMobile]}><View style={[s.timelineTrack, index === milestones.length - 1 && s.timelineTrackLast]}><View style={[s.timelinePoint, index === 2 && s.timelinePointActive]}><Icon name={milestone.icon as IconName} size={index === 2 ? 24 : 20} color={index === 2 ? colors.white : colors.primary} /></View></View><View style={s.timelineBody}><Text style={s.timelineDate}>{milestone.date}</Text><Text style={s.timelineTitle}>{milestone.title}</Text><View style={s.timelineItems}>{milestone.items.map((item) => <Text key={item} style={s.timelineBullet}>—  {item}</Text>)}</View></View><Text style={[s.timelineMark, mobile && s.timelineMarkMobile]}>0{index + 1}</Text></View>)}</View></Frame></View>;
}

function Closing({ mobile, onLayout, openDialog }: { mobile: boolean; onLayout: (event: LayoutChangeEvent) => void; openDialog: (dialog: Dialog) => void }) {
  const wearableWidth = mobile ? 220 : 325;
  return <View onLayout={onLayout} style={[s.closing, mobile && s.closingMobile]}><Image source={images.technology} resizeMode="cover" style={s.coverBackground} /><View pointerEvents="none" style={s.closingShade} /><Frame mobile={mobile} style={s.closingFrame}><View style={[s.closingCopy, mobile && s.closingCopyMobile]}><Text accessibilityRole="header" style={[s.closingTitle, mobile && s.closingTitleMobile]}>Chăm sóc sức khỏe{`\n`}cần cả công nghệ{`\n`}và sự dịu dàng.</Text><BodyText dark style={s.closingText}>Cùng WeCare mở ra một cách gần gũi hơn để nhìn về sức khỏe của mỗi người.</BodyText><PrimaryAction label="Bắt đầu cùng WeCare" onPress={() => openDialog({ title: 'Kết nối cùng WeCare', text: 'Cảm ơn bạn đã quan tâm đến WeCare. Nhóm dự án sẽ đồng hành cùng bạn trong hành trình tìm hiểu và trải nghiệm giải pháp.', image: 'wearable' })} /></View><View pointerEvents="none" style={[s.closingProductZone, mobile && s.closingProductZoneMobile]}><View style={s.closingOrb} /><Image source={images.wearable} resizeMode="contain" style={[s.closingWearable, { width: wearableWidth, height: wearableWidth * WEARABLE_RATIO }]} /></View></Frame></View>;
}

function Footer({ mobile, navigate }: { mobile: boolean; navigate: (name: SectionName) => void }) {
  return <View style={s.footerShell}><Frame mobile={mobile} style={[s.footer, mobile && s.footerMobile]}><Image source={images.logoReverse} resizeMode="contain" style={s.footerLogo} /><View style={[s.footerNav, mobile && s.footerNavMobile]}>{navigation.map((item) => <NavLink key={item.target} label={item.label} dark onPress={() => navigate(item.target)} />)}</View><Text style={s.copyright}>© 2026 WeCare{`\n`}Vì những ngày mai khỏe hơn.</Text></Frame></View>;
}

function InfoModal({ dialog, mobile, close }: { dialog: Dialog; mobile: boolean; close: () => void }) {
  return <Modal visible={Boolean(dialog)} transparent animationType="fade" onRequestClose={close}><Pressable style={s.modalBackdrop} onPress={close}><Pressable style={[s.modalCard, mobile && s.modalCardMobile]} onPress={(event) => event.stopPropagation()}><Pressable accessibilityRole="button" accessibilityLabel="Đóng" onPress={close} style={s.modalClose}><Icon name="close" size={20} /></Pressable><Text accessibilityRole="header" style={s.modalTitle}>{dialog?.title}</Text><BodyText style={s.modalText}>{dialog?.text}</BodyText>{dialog?.image ? <Image source={dialog.image === 'app' ? images.appDashboard : images.wearable} resizeMode="contain" style={dialog.image === 'app' ? s.modalAppImage : s.modalWearable} /> : null}<Text style={s.modalNote}>Các nội dung sức khỏe trong bản mô phỏng chỉ mang tính minh họa.</Text></Pressable></Pressable></Modal>;
}

function PrimaryAction({ label, onPress }: { label: string; onPress: () => void }) { return <Pressable accessibilityRole="button" onPress={onPress} style={({ pressed }) => [s.primaryAction, pressed && s.pressed]}><Text style={s.primaryActionText}>{label}</Text><Icon name="arrow" size={16} color={colors.primary} /></Pressable>; }
function OutlineAction({ label, onPress, darkText = false }: { label: string; onPress: () => void; darkText?: boolean }) { return <Pressable accessibilityRole="button" onPress={onPress} style={({ pressed }) => [s.outlineAction, darkText && s.outlineActionDark, pressed && s.pressed]}><Text style={[s.outlineActionText, darkText && s.outlineActionTextDark]}>{label}</Text><Icon name="arrow" size={15} color={darkText ? colors.primary : colors.white} /></Pressable>; }
function SmallAction({ label, onPress }: { label: string; onPress: () => void }) { return <Pressable accessibilityRole="button" onPress={onPress} style={({ pressed }) => [s.smallAction, pressed && s.pressed]}><Text style={s.smallActionText}>{label}</Text></Pressable>; }
function NavLink({ label, onPress, dark = false, mobile = false }: { label: string; onPress: () => void; dark?: boolean; mobile?: boolean }) { return <Pressable accessibilityRole="link" onPress={onPress} style={({ pressed }) => [mobile && s.mobileNavItem, pressed && s.pressed]}><Text style={[s.navText, dark && s.navTextDark, mobile && s.mobileNavText]}>{label}</Text></Pressable>; }

const s = StyleSheet.create({
  app: { flex: 1, backgroundColor: '#F8FBF9' }, scroll: { flex: 1 }, scrollContent: { backgroundColor: '#F8FBF9' }, progress: { position: 'absolute', top: 0, left: 0, height: 3, backgroundColor: '#A8FFD0', zIndex: 100, shadowColor: '#A8FFD0', shadowOpacity: 0.8, shadowRadius: 8 },
  heroShell: { minHeight: 760, backgroundColor: '#06291F', overflow: 'hidden', position: 'relative' }, heroShellMobile: { minHeight: 960 }, heroTexture: { position: 'absolute', width: '100%', height: '100%', opacity: 0.3 }, heroGrid: { position: 'absolute', width: '100%', height: '100%', opacity: 0.22, backgroundColor: 'transparent', borderLeftWidth: 1, borderRightWidth: 1, borderColor: 'rgba(171,255,208,.24)' }, heroFrame: { minHeight: 760, position: 'relative' }, header: { height: 92, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', zIndex: 20 }, logo: { width: 160, height: 40 }, logoMobile: { width: 132, height: 35 }, navigation: { flexDirection: 'row', alignItems: 'center', gap: 24 }, navText: { fontFamily: fonts.medium, fontSize: 12, color: colors.ink }, navTextDark: { color: '#E7F8EF' }, menuButton: { padding: 8 }, mobileMenu: { position: 'absolute', top: 72, left: 20, right: 20, zIndex: 30, paddingVertical: 10, paddingHorizontal: 12, borderRadius: 8, backgroundColor: '#E9FFF1', shadowColor: '#031A13', shadowOpacity: 0.25, shadowRadius: 22, elevation: 8 }, mobileNavItem: { paddingHorizontal: 8, paddingVertical: 10 }, mobileNavText: { fontSize: 15, color: colors.primary },
  heroContent: { minHeight: 590, justifyContent: 'center', position: 'relative' }, heroContentMobile: { minHeight: 820, justifyContent: 'flex-start', paddingTop: 44 }, heroCopy: { width: '54%', maxWidth: 680, zIndex: 3 }, heroCopyMobile: { width: '100%', maxWidth: 390 }, heroTitle: { fontFamily: fonts.bold, fontSize: 72, lineHeight: 73, letterSpacing: 0, color: colors.white }, heroTitleTablet: { fontSize: 58, lineHeight: 60 }, heroTitleMobile: { fontSize: 44, lineHeight: 47 }, heroTitleTiny: { fontSize: 41, lineHeight: 44 }, heroBody: { maxWidth: 500, marginTop: 25, fontFamily: fonts.regular, fontSize: 16, lineHeight: 25, color: '#D7E8DF' }, heroBodyMobile: { maxWidth: 350, fontSize: 15, lineHeight: 23, marginTop: 19 }, actionRow: { marginTop: 28, flexDirection: 'row', flexWrap: 'wrap', gap: 12 }, primaryAction: { minHeight: 48, paddingHorizontal: 20, borderRadius: 4, flexDirection: 'row', alignItems: 'center', gap: 15, backgroundColor: '#BFF6D6' }, primaryActionText: { fontFamily: fonts.semiBold, fontSize: 13, color: colors.primary }, outlineAction: { minHeight: 48, paddingHorizontal: 20, borderRadius: 4, borderWidth: 1, borderColor: 'rgba(229,255,239,.55)', flexDirection: 'row', alignItems: 'center', gap: 15 }, outlineActionDark: { borderColor: '#175442', alignSelf: 'flex-start', marginTop: 26 }, outlineActionText: { fontFamily: fonts.semiBold, fontSize: 13, color: colors.white }, outlineActionTextDark: { color: colors.primary }, smallAction: { borderWidth: 1, borderColor: 'rgba(229,255,239,.5)', borderRadius: 3, paddingHorizontal: 14, paddingVertical: 10 }, smallActionText: { fontFamily: fonts.medium, fontSize: 11, color: colors.white },
  heroProductZone: { position: 'absolute', right: -30, top: 10, width: '59%', height: '100%', justifyContent: 'center', alignItems: 'center' }, heroProductZoneMobile: { width: '100%', right: -28, top: 545, height: 365, alignItems: 'flex-end' }, productHalo: { position: 'absolute', width: 490, height: 490, borderRadius: 245, backgroundColor: 'rgba(136,255,188,.13)', borderWidth: 1, borderColor: 'rgba(184,255,213,.35)', transform: [{ scaleX: 1.25 }] }, productHaloMobile: { width: 285, height: 285, borderRadius: 143 }, heroProducts: { zIndex: 2, transform: [{ perspective: 1100 }, { rotateY: '-8deg' }, { rotateZ: '1deg' }, { translateY: -4 }] }, heroProductNote: { position: 'absolute', right: 4, bottom: 94, fontFamily: fonts.handwriting, fontSize: 21, lineHeight: 26, color: '#D5F9E3', transform: [{ rotate: '-6deg' }] }, scrollPrompt: { position: 'absolute', bottom: 26, left: 0, flexDirection: 'row', alignItems: 'center', gap: 10 }, scrollPromptMobile: { display: 'none' }, scrollLine: { width: 32, height: 1, backgroundColor: '#BFF6D6' }, scrollText: { fontFamily: fonts.medium, fontSize: 10, color: '#CDEBD9' },
  manifesto: { paddingVertical: 138, backgroundColor: '#FFFFFF' }, manifestoMobile: { paddingVertical: 84 }, manifestoIndex: { fontFamily: fonts.medium, fontSize: 10, letterSpacing: 1.6, color: '#4B7D69', marginBottom: 30 }, manifestoTitle: { maxWidth: 1040, fontFamily: fonts.semiBold, fontSize: 50, lineHeight: 61, letterSpacing: 0, color: colors.ink }, manifestoTitleMobile: { fontSize: 32, lineHeight: 40 }, manifestoFoot: { marginTop: 56, flexDirection: 'row', alignItems: 'flex-start', gap: 16, maxWidth: 580, marginLeft: '42%' }, manifestoFootMobile: { marginTop: 36, marginLeft: 0 }, mintDot: { width: 9, height: 9, borderRadius: 5, backgroundColor: '#7DDAA4', marginTop: 6 }, manifestoText: { flex: 1, fontSize: 15, lineHeight: 24 },
  ecosystem: { paddingVertical: 126, backgroundColor: '#EFF8F3', overflow: 'hidden' }, ecosystemMobile: { paddingVertical: 76 }, splitHeading: { flexDirection: 'row', gap: 26, alignItems: 'flex-start' }, splitHeadingMobile: { gap: 15 }, headingCopy: { flex: 1, minWidth: 0 }, sectionNumber: { width: 40, paddingTop: 6, fontFamily: fonts.medium, fontSize: 11, letterSpacing: 1.5, color: '#4E866E' }, sectionTitle: { fontFamily: fonts.semiBold, fontSize: 48, lineHeight: 55, color: colors.ink }, sectionTitleMobile: { fontSize: 32, lineHeight: 38 }, sectionLead: { maxWidth: 450, fontSize: 15, lineHeight: 23, marginTop: 18 }, orbitStage: { height: 720, position: 'relative', marginTop: 20, alignItems: 'center', justifyContent: 'center' }, orbitStageMobile: { height: 690, marginTop: 26 }, orbitOuter: { position: 'absolute', width: 610, height: 610, borderRadius: 305, borderWidth: 1, borderColor: 'rgba(43,111,84,.27)', transform: [{ scaleX: 1.26 }] }, orbitOuterMobile: { width: 304, height: 304, borderRadius: 152, transform: [{ scaleX: 1.14 }] }, orbitInner: { position: 'absolute', width: 360, height: 360, borderRadius: 180, borderWidth: 1, borderColor: 'rgba(43,111,84,.19)', transform: [{ scaleX: 1.24 }] }, orbitInnerMobile: { width: 190, height: 190, borderRadius: 95 }, orbitCore: { width: 250, height: 410, alignItems: 'center', justifyContent: 'center', zIndex: 3 }, orbitCoreMobile: { width: 150, height: 300 }, orbitPhone: { width: '100%', height: '100%', transform: [{ perspective: 950 }, { rotateY: '-9deg' }, { rotateZ: '2deg' }] }, station: { position: 'absolute', zIndex: 5, minWidth: 184, maxWidth: 212, paddingVertical: 15, paddingHorizontal: 17, backgroundColor: '#0A3428', borderRadius: 3, shadowColor: '#0A3428', shadowOpacity: 0.17, shadowRadius: 22, elevation: 5 }, stationOrdinal: { fontFamily: fonts.medium, fontSize: 10, letterSpacing: 1.2, color: '#BFF6D6' }, stationTitle: { marginTop: 7, paddingRight: 26, fontFamily: fonts.semiBold, fontSize: 13, lineHeight: 18, color: colors.white }, stationArrow: { position: 'absolute', right: 14, bottom: 15 }, stationA: { left: '3%', top: 96 }, stationB: { right: '1%', top: 138 }, stationC: { left: '9%', bottom: 100 }, stationD: { right: '5%', bottom: 84 }, stationTabletA: { left: 0, top: 90 }, stationTabletB: { right: 0, top: 130 }, stationTabletC: { left: '3%', bottom: 80 }, stationTabletD: { right: 0, bottom: 65 }, stationMobileA: { left: 0, top: 12, minWidth: 160 }, stationMobileB: { right: 0, top: 126, minWidth: 160 }, stationMobileC: { left: 0, bottom: 114, minWidth: 160 }, stationMobileD: { right: 0, bottom: 4, minWidth: 160 },
  technology: { minHeight: 650, paddingVertical: 112, backgroundColor: '#082E24', position: 'relative', overflow: 'hidden' }, technologyMobile: { paddingVertical: 74 }, coverBackground: { position: 'absolute', width: '100%', height: '100%', opacity: 0.65 }, techShade: { position: 'absolute', width: '100%', height: '100%', backgroundColor: 'rgba(3,31,23,.56)' }, technologyFrame: { position: 'relative' }, techHeading: { flexDirection: 'row', gap: 26 }, techHeadingMobile: { gap: 15 }, sectionNumberDark: { width: 40, paddingTop: 7, fontFamily: fonts.medium, fontSize: 11, letterSpacing: 1.5, color: '#BFF6D6' }, techTitle: { fontFamily: fonts.semiBold, fontSize: 48, lineHeight: 55, color: colors.white }, techTitleMobile: { fontSize: 32, lineHeight: 38 }, techLead: { maxWidth: 460, marginTop: 18, fontSize: 15, lineHeight: 23 }, dataRail: { marginTop: 78, flexDirection: 'row', justifyContent: 'space-between', gap: 18, position: 'relative' }, dataRailMobile: { marginTop: 50, flexDirection: 'column', gap: 25 }, dataNode: { width: '18%', position: 'relative' }, dataNodeMobile: { width: '100%', paddingLeft: 82, minHeight: 78 }, dataNumber: { width: 28, height: 28, borderRadius: 14, borderWidth: 1, borderColor: 'rgba(206,255,226,.7)', alignItems: 'center', justifyContent: 'center' }, dataNumberText: { fontFamily: fonts.medium, fontSize: 10, color: '#D7FFE6' }, dataIcon: { width: 64, height: 64, borderRadius: 32, borderWidth: 1, borderColor: 'rgba(206,255,226,.55)', alignItems: 'center', justifyContent: 'center', marginTop: 18 }, dataTitle: { marginTop: 20, fontFamily: fonts.semiBold, fontSize: 14, lineHeight: 19, color: colors.white }, dataText: { marginTop: 8, fontFamily: fonts.regular, fontSize: 12, lineHeight: 18, color: '#C6DED3' }, dataConnector: { position: 'absolute', width: '82%', height: 1, backgroundColor: 'rgba(201,255,220,.38)', right: '-75%', top: 60, zIndex: -1 }, dataConnectorDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#BFF6D6', position: 'absolute', right: 0, top: -2 },
  capabilities: { paddingVertical: 126, backgroundColor: '#FFFFFF' }, capabilitiesMobile: { paddingVertical: 76 }, capabilityIntro: { flexDirection: 'row', gap: 26 }, capabilityIntroMobile: { gap: 15 }, capabilityList: { marginTop: 72, flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', rowGap: 0 }, capabilityRow: { width: '31%', minHeight: 190, paddingVertical: 22, borderTopWidth: 1, borderTopColor: '#D5E5DE', position: 'relative' }, capabilityRowMobile: { width: '100%', minHeight: 152, paddingVertical: 20, paddingLeft: 64 }, capabilityNumber: { fontFamily: fonts.medium, fontSize: 10, letterSpacing: 1.2, color: '#588371' }, capabilityIcon: { marginTop: 21, width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center', backgroundColor: '#E4F3EA' }, capabilityCopy: {}, capabilityTitle: { marginTop: 19, fontFamily: fonts.semiBold, fontSize: 17, lineHeight: 22, color: colors.ink }, capabilityText: { marginTop: 7, fontSize: 13, lineHeight: 20 },
  humanStory: { minHeight: 560, flexDirection: 'row', backgroundColor: '#DDF2E7' }, humanStoryMobile: { minHeight: 0, flexDirection: 'column' }, storyImageWrap: { width: '57%', minHeight: 560, position: 'relative', overflow: 'hidden' }, storyImageWrapMobile: { width: '100%', height: 330, minHeight: 330 }, storyImage: { position: 'absolute', width: '100%', height: '100%' }, storyImageShade: { position: 'absolute', width: '100%', height: '100%', backgroundColor: 'rgba(3,43,31,.16)' }, storyCaption: { position: 'absolute', left: 48, bottom: 42, fontFamily: fonts.handwriting, fontSize: 31, lineHeight: 37, color: colors.white }, storyPanel: { width: '43%', paddingHorizontal: 72, paddingVertical: 74, justifyContent: 'center' }, storyPanelMobile: { width: '100%', paddingHorizontal: 20, paddingVertical: 60 }, storyTitle: { marginTop: 22, fontFamily: fonts.semiBold, fontSize: 42, lineHeight: 49, color: colors.ink }, storyTitleMobile: { fontSize: 32, lineHeight: 38 }, storyText: { maxWidth: 420, marginTop: 21, fontSize: 15, lineHeight: 23 },
  roadmap: { paddingVertical: 130, backgroundColor: '#F9FCFA' }, roadmapMobile: { paddingVertical: 76 }, roadmapHeading: { flexDirection: 'row', gap: 26 }, roadmapHeadingMobile: { gap: 15 }, roadmapLead: { maxWidth: 430, marginTop: 18, fontSize: 15, lineHeight: 23 }, timeline: { marginTop: 75, maxWidth: 960 }, timelineItem: { flexDirection: 'row', minHeight: 190, position: 'relative' }, timelineItemMobile: { minHeight: 220 }, timelineTrackLast: {}, timelineTrack: { width: 72, alignItems: 'center', position: 'relative', borderLeftWidth: 1, borderLeftColor: '#BFD7CB', marginLeft: 17 }, timelinePoint: { position: 'absolute', top: 0, left: -17, width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center', backgroundColor: '#E6F4EB', borderWidth: 1, borderColor: '#71A38C' }, timelinePointActive: { width: 46, height: 46, borderRadius: 23, left: -23, top: -6, backgroundColor: colors.primary, borderColor: '#BFF6D6', shadowColor: '#76F0A7', shadowOpacity: 0.65, shadowRadius: 17, elevation: 6 }, timelineBody: { flex: 1, paddingBottom: 46 }, timelineDate: { fontFamily: fonts.medium, fontSize: 11, letterSpacing: 1.1, color: '#4E866E' }, timelineTitle: { marginTop: 9, fontFamily: fonts.semiBold, fontSize: 24, lineHeight: 30, color: colors.ink }, timelineItems: { marginTop: 14 }, timelineBullet: { fontFamily: fonts.regular, fontSize: 13, lineHeight: 22, color: colors.muted }, timelineMark: { width: 80, fontFamily: fonts.bold, fontSize: 54, lineHeight: 56, color: '#DFECE5', textAlign: 'right' }, timelineMarkMobile: { display: 'none' },
  closing: { minHeight: 590, overflow: 'hidden', backgroundColor: '#062D21', position: 'relative' }, closingMobile: { minHeight: 710 }, closingShade: { position: 'absolute', width: '100%', height: '100%', backgroundColor: 'rgba(2,29,20,.65)' }, closingFrame: { minHeight: 590, position: 'relative', justifyContent: 'center' }, closingCopy: { width: '60%', maxWidth: 710, zIndex: 2 }, closingCopyMobile: { width: '100%', position: 'absolute', top: 68, left: 20, right: 20 }, closingTitle: { fontFamily: fonts.semiBold, fontSize: 52, lineHeight: 58, color: colors.white }, closingTitleMobile: { fontSize: 35, lineHeight: 41 }, closingText: { maxWidth: 450, marginTop: 21, marginBottom: 27, fontSize: 15, lineHeight: 23 }, closingProductZone: { position: 'absolute', right: 60, width: 430, height: '100%', alignItems: 'center', justifyContent: 'center' }, closingProductZoneMobile: { right: -24, bottom: -16, width: 270, height: 330, justifyContent: 'flex-end' }, closingOrb: { position: 'absolute', width: 330, height: 330, borderRadius: 165, backgroundColor: 'rgba(152,255,196,.12)', borderWidth: 1, borderColor: 'rgba(190,255,216,.3)', transform: [{ scaleX: 1.2 }] }, closingWearable: { zIndex: 2, transform: [{ perspective: 1000 }, { rotateY: '-13deg' }, { rotateZ: '9deg' }] },
  footerShell: { backgroundColor: '#05241B' }, footer: { minHeight: 128, paddingVertical: 25, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 24 }, footerMobile: { minHeight: 240, flexDirection: 'column', justifyContent: 'center', alignItems: 'flex-start' }, footerLogo: { width: 142, height: 35 }, footerNav: { flexDirection: 'row', flexWrap: 'wrap', gap: 17, justifyContent: 'center' }, footerNavMobile: { gap: 14, justifyContent: 'flex-start' }, copyright: { fontFamily: fonts.regular, fontSize: 10, lineHeight: 16, color: '#B8D0C4', textAlign: 'right' },
  modalBackdrop: { flex: 1, padding: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(2,31,23,.69)' }, modalCard: { width: '100%', maxWidth: 520, maxHeight: '90%', padding: 32, borderRadius: 7, backgroundColor: '#F8FBF9', shadowColor: '#000', shadowOpacity: 0.25, shadowRadius: 30, elevation: 12 }, modalCardMobile: { padding: 24 }, modalClose: { position: 'absolute', top: 13, right: 13, padding: 8, zIndex: 2 }, modalTitle: { paddingRight: 36, fontFamily: fonts.semiBold, fontSize: 26, lineHeight: 32, color: colors.ink }, modalText: { marginTop: 14, fontSize: 14, lineHeight: 22 }, modalAppImage: { width: 180, height: 320, alignSelf: 'center', marginTop: 16 }, modalWearable: { width: 190, height: 190 * WEARABLE_RATIO, alignSelf: 'center', marginTop: 15 }, modalNote: { marginTop: 14, fontFamily: fonts.regular, fontSize: 10, lineHeight: 15, color: colors.muted, textAlign: 'center' }, pressed: { opacity: 0.72, transform: [{ translateY: 1 }] },
});
